# Generated by Django 4.0 on 2022-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oClinicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='blood1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=7),
        ),
        migrations.AlterField(
            model_name='information',
            name='dia1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=7),
        ),
    ]
